defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "_notes"
    values:
      layout: note
      type: note
collections:
  notes:
    permalink: /:slug
    output: true
