defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "_notes"
    values:
      layout: note
      type: note
      excerpt_separator: <!--more-->
collections:
  notes:
    permalink: /:slug
    output: true



markdown: kramdown
highlighter: rouge
kramdown:
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1